name: norm_request
description: A new Flutter project.

publish_to: 'none_request' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.3.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.16.0
  cloud_firestore: ^3.1.6
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  fl_chart: ^0.41.0
  blobs: ^2.0.0
  google_mobile_ads: ^1.2.0
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.0
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/icon/
    - images/logo/

flutter_native_splash:
  image: "images/icons/icon.png"
  color: "000000"
